export const ErrorCodes = {
  // Auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS:  'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED:   'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',

  // OTP
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'OTP_MAX_ATTEMPTS_EXCEEDED',

  //Authorization
  FORBIDDEN: 'FORBIDDEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Session
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  //General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND:             'NOT_FOUND',
  CONFLICT:              'CONFLICT',

  // Subscription
  SUBSCRIPTION_NOT_FOUND:    'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',

  // Payment
  PAYMENT_FAILED:    'PAYMENT_FAILED',
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',

  //Rate Limit
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
} as const;